<a href="https://colab.research.google.com/github/Ariara61/Jiwonee/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [2]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(np.intersect1d(Z1, Z2))

[0 2 3 4]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-3-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

It is not True.

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [4]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [5]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [6]:
array30 = np.random.rand(5) * 10
int_array30 = np.floor(array30)

print(int_array30)

[2. 1. 1. 1. 2.]


In [7]:
array30 = np.random.rand(5) * 10
int_array30 = array30.astype(int)

print(int_array30)

[0 3 7 1 7]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
array31 = np.zeros((5,5))
array31 += np.arange(5)
print(array31)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [9]:
array32 = np.array(np.random.random(10))
print(np.sort(array32))

[0.04358139 0.17994608 0.18068754 0.22559365 0.72569887 0.8108052
 0.85485217 0.92074318 0.97155857 0.99901435]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [10]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

Array A and B are not equal.

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [11]:
cart_coords = np.random.random((10, 2))
print(cart_coords)

x = cart_coords[:, 0]
y = cart_coords[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

print(r)
print(theta)

[[0.7572153  0.10860882]
 [0.6441347  0.51688968]
 [0.78483983 0.48323571]
 [0.39167301 0.55368642]
 [0.2145018  0.09581309]
 [0.13849093 0.71516599]
 [0.03961373 0.92932607]
 [0.01860792 0.27739799]
 [0.54563633 0.76047113]
 [0.23148342 0.49345923]]
[0.76496463 0.82588404 0.92167798 0.6782156  0.23492801 0.72845187
 0.93016998 0.2780214  0.9359676  0.54505649]
[0.14246026 0.67623664 0.55189278 0.9551269  0.42008736 1.37951523
 1.52819582 1.50381643 0.94842318 1.13217004]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [12]:
Z = np.array(np.random.random(10))
Z[Z.argmax()] = 0
print(Z)

[0.29784568 0.         0.1263705  0.82334137 0.30262175 0.21155034
 0.16874626 0.8526229  0.0247923  0.60154842]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [20]:
Z = np.arange(100)
v = np.random.uniform(0, 100)

distances = np.abs(Z - v)
index = np.argmin(distances)
Z[index]

98

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [25]:
Z = np.arange(9).reshape(3,3)

# ndenumerate() 사용
for index, value in np.ndenumerate(Z):
  print(index, value)

# ndindex() 사용
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [26]:
n = 5    # size of a 2D array
p = 3    # the number of elements that you want to place
Z = np.zeros((n, n))

indices = np.random.choice(range(n*n), p, replace = False)
np.put(Z, indices, 1)

print(Z)

[[1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [36]:
# column 1
Z = np.random.randint(0, 10, (3, 3))
n = 0
print(Z)

sorted_indices = np.argsort(Z[:, n])
print(Z[sorted_indices])

[[6 7 8]
 [2 3 9]
 [8 6 5]]
[[2 3 9]
 [6 7 8]
 [8 6 5]]


In [35]:
# column 2
Z = np.random.randint(0, 10, (3, 3))
n = 1
print(Z)

sorted_indices = np.argsort(Z[:, n])
print(Z[sorted_indices])

[[5 4 0]
 [9 5 7]
 [0 6 5]]
[[5 4 0]
 [9 5 7]
 [0 6 5]]


In [38]:
# column 3
Z = np.random.randint(0, 10, (3, 3))
n = 2
print(Z)

sorted_indices = np.argsort(Z[:, n])
print(Z[sorted_indices])

[[4 0 3]
 [6 9 6]
 [8 2 4]]
[[4 0 3]
 [8 2 4]
 [6 9 6]]
